# Generated by Django 3.2.12 on 2022-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(blank=True, null=True)),
                ('totalcost', models.FloatField(blank=True, null=True)),
                ('modified', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, max_length=250, null=True)),
                ('unitcost', models.FloatField(blank=True, null=True)),
                ('itemcount', models.IntegerField(blank=True, null=True)),
                ('variant', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(blank=True, max_length=250, null=True)),
                ('item1id', models.IntegerField(blank=True, null=True)),
                ('count1', models.IntegerField(blank=True, null=True)),
                ('item2id', models.IntegerField(blank=True, null=True)),
                ('count2', models.IntegerField(blank=True, null=True)),
                ('item3id', models.IntegerField(blank=True, null=True)),
                ('count3', models.IntegerField(blank=True, null=True)),
                ('modified', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
