# Generated by Django 3.2.12 on 2022-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='itemcount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
